main/urls.py
from django.urls import path
from main.views import *
from melihat_chart.views import melihat_chart, daily_top,weekly_top, monthly_top, yearly_top
from play_podcast.views import play_podcast
from play_song.views import add_song_to_playlist, play_song
from play_user_playlist.views import play_user_playlist

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('user_login/', user_login, name='user_login'),
    path('register-option/', register_option, name='register_option'),
    path('register-option/register-user/', register_user, name='register_user'),
    path('register-option/register-label/', register_label, name='register_label'),
    path('homepage/', homepage, name="homepage"),
    path('logout/', logout, name="logout"),
    path('play-podcast/<uuid:podcast_id>/', play_podcast, name='play_podcast'),
    path('play-song/<uuid:song_id>/', play_song, name='play_song'),
    path('melihat-chart/', melihat_chart, name='melihat_chart'),
    path('melihat-chart/daily-top/', daily_top, name='daily_top'),
    path('melihat-chart/weekly-top/', weekly_top, name='weekly_top'),
    path('melihat-chart/monthly-top/', monthly_top, name='monthly_top'),
    path('melihat-chart/yearly-top/', yearly_top, name='yearly_top'),
    path('play-user-playlist/<uuid:user_playlist_id>/', play_user_playlist, name='play_user_playlist'),
    path('index/', index, name='index'),
    path('album_list/', album_list, name='album_list'),
    path('album_detail/<str:album_id>/', album_detail, name='album_detail'),
    path('delete_album/<str:album_id>/', delete_album, name='delete_album'),
    path('song_detail/<str:song_id>/', song_detail, name='song_detail'),
    path('delete_song/<str:song_id>/', delete_song, name='delete_song'),
    path('royalty_list/', royalty_list, name='royalty_list'),  
    path('create_album/', create_album, name='create_album'),
    path('create_song_songwriter/<str:album_id>/', create_song_songwriter, name='create_song_songwriter'),
    path('create_song_artist/<str:album_id>/', create_song_artist, name='create_song_artist'),
    path('play-song/<uuid:song_id>/add-song-to-playlist/', add_song_to_playlist, name='add_song_to_playlist'),
]

marmut/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('playlist/', include('playlist.urls')),
    path('', include('play_song.urls')),
    path('', include('melihat_chart.urls')),
]

play_song/urls.py
from django.urls import path
from play_song.views import add_song_to_playlist, play_song, update_play_count

app_name = 'play_song'

urlpatterns = [
    path('play-song/<uuid:song_id>/', play_song, name='play_song'),
    path('update-play-count/<uuid:song_id>/', update_play_count, name='update-play-count'),
    path('play-song/<uuid:song_id>/add-song-to-playlist/', add_song_to_playlist, name='add_song_to_playlist'),
]

playlist/urls.py
from django.urls import path
from playlist.views import *

app_name = 'playlist'

urlpatterns = [
  path('', show_playlist, name='show_playlist'),
  path('playlist_detail/<str:id_playlist>', playlist_detail, name='playlist_detail'),
  path('add_playlist/', add_playlist, name='add_playlist'),
  path('delete_playlist/<str:id_playlist>', delete_playlist, name="delete_playlist"),
  path('add_song/<str:id_playlist>', add_song, name="add_song"),
  path('playlist_detail/delete_song/<str:id_playlist>/<str:id_song>', delete_song, name="delete_song")
]

play_song/models.py
from django.db import models

# Create your models here.

play_song/views.py
from django.shortcuts import render
from django.db import DatabaseError, InternalError, connection
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from django.db import connection
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

def play_song(request, song_id):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT K.judul AS "Judul",
                array_agg(G.genre) AS "Genre",
                AK.nama AS "Artist",
                array_agg(SW.nama) AS "Songwriter",
                K.durasi AS "Durasi",
                K.tanggal_rilis AS "Tanggal Rilis",
                K.tahun AS "Tahun",
                COALESCE(SUM(S.total_play), 0) AS "Total Play",
                COALESCE(SUM(S.total_download), 0) AS "Total Downloads",
                A.judul AS "Album"
            FROM SONG S
            JOIN KONTEN K ON S.id_konten = K.id
            LEFT JOIN GENRE G ON K.id = G.id_konten
            LEFT JOIN ARTIST AR ON S.id_artist = AR.id
            LEFT JOIN AKUN AK ON AR.email_akun = AK.email
            LEFT JOIN SONGWRITER_WRITE_SONG SWS ON S.id_konten = SWS.id_song
            LEFT JOIN SONGWRITER SWR ON SWS.id_songwriter = SWR.id
            LEFT JOIN AKUN SW ON SWR.email_akun = SW.email
            LEFT JOIN ALBUM A ON S.id_album = A.id
            WHERE K.id = %s
            GROUP BY K.id, AK.nama, A.judul
        """, [str(song_id)])  # Convert UUID to string if necessary
        song_detail = cursor.fetchall()

    if not song_detail:
        return render(request, 'error.html', {'message': 'Song not found'})

    print("Song details fetched:", song_detail)  # Check what data is fetched from the database

    song_data = song_detail[0]
    context = {
        'song_detail': {
            'judul': song_data[0],
            'genres': song_data[1],
            'artist': song_data[2],
            'songwriters': song_data[3],
            'durasi': song_data[4],
            'tanggal_rilis': song_data[5],
            'tahun': song_data[6],
            'total_play': song_data[7],
            'total_downloads': song_data[8],
            'album': song_data[9],
        },
    }

    return render(request, 'play_song.html', context)

def add_song_to_playlist(request, song_id):
    success_message = None
    error_message = None
    playlist_name = None
    song_title = None
    artist_name = None
    playlists = None
    other_playlist_id = None

    email_pengguna = request.COOKIES.get('email')

    with connection.cursor() as cursor:
        cursor.execute("""
                SELECT k.judul, a.nama AS artist
                FROM song s
                JOIN konten k ON s.id_konten = k.id
                JOIN artist ar ON s.id_artist = ar.id
                JOIN akun a ON ar.email_akun = a.email
                WHERE s.id_konten = %s;
            """, [song_id])
        song_data = cursor.fetchone()
        
        if song_data:
            song_title, artist_name = song_data

        if request.method == 'POST':
            other_playlist_id = request.POST.get('other_playlist_id')
            
            cursor.execute("SELECT judul FROM user_playlist WHERE id_playlist = %s", [other_playlist_id])
            playlist_name_query = cursor.fetchone()
            if playlist_name_query:
                playlist_name = playlist_name_query[0]
            
            try:
                cursor.execute("INSERT INTO playlist_song (id_playlist, id_song) VALUES (%s, %s);", 
                            [other_playlist_id, song_id])
                connection.commit()
                success_message = f"Berhasil menambahkan Lagu dengan judul '{song_title}' oleh '{artist_name}' ke '{playlist_name}'!"
            except (DatabaseError, InternalError) as e:
                connection.rollback()
                if 'marmut.check_duplicate_song_on_playlist' in str(e):
                    error_message = f"Lagu '{song_title}' sudah ada dalam playlist '{playlist_name}'"
                else:
                    error_message = "Gagal menambahkan lagu ke playlist"

    
        cursor.execute("""
            SELECT id_playlist, judul 
            FROM user_playlist 
            WHERE email_pembuat = %s;
        """, [email_pengguna])
        playlists = cursor.fetchall()

        context = {
            'song_id': song_id,
            'song_title': song_title,
            'artist_name': artist_name,
            'success_message': success_message,
            'error_message': error_message,
            'playlist_name': playlist_name,
            'playlists' : playlists,
            'other_playlist' : other_playlist_id
        }

        cursor.close()
        connection.close()

        return render(request, 'add_song_to_playlist.html', context)


@csrf_exempt
def update_play_count(request, song_id):
    if request.method == 'POST':
        print("Received request to update play count for song ID:", song_id)  # Print debug info
        with connection.cursor() as cursor:
            cursor.execute("""
                UPDATE SONG SET total_play = total_play + 1 WHERE id_konten = %s
                RETURNING total_play;
            """, [song_id])
            new_total_plays = cursor.fetchone()[0]
            print("New total plays:", new_total_plays)  # Print updated play count

        return JsonResponse({'success': True, 'new_total_plays': new_total_plays})
    else:
        return JsonResponse({'success': False, 'message': 'Invalid request'}, status=400)

play_song/templates/add_song_to_playlist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

{% block meta %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Add Song to Playlist</title>
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <style>
        body {
            font-family: 'Open Sans', sans-serif;
            margin: 0;
            background: linear-gradient(to right, red, blue);
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            color: white; /* Set text color to white */
        }

        .container {
            background-color: rgba(255, 255, 255, 0.2); /* Semi-transparent white */
            padding: 30px;
            border-radius: 20px; /* Rounded corners */
            box-shadow: 0 8px 16px rgba(0,0,0,0.1); /* Soft shadow for depth */
            width: 80%;
            max-width: 500px; /* Control the maximum width */
            text-align: center;
        }

        select, button {
            width: 100%; /* Full width */
            padding: 10px;
            margin-top: 10px;
            border: none;
            border-radius: 5px;
            background-color: #222; /* Dark background for inputs and buttons */
            color: white;
            outline: none;
        }

        button {
            background-color: black;
            color: white;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        button:hover {
            background-color: #4CAF50; /* Hijau ketika di-hover */
        }

        .song-info {
            display: flex; /* Aktifkan flexbox */
            flex-direction: column; /* Menyusun item secara vertikal */
            justify-content: center; /* Pusatkan item secara vertikal di container */
            align-items: center; /* Pusatkan item secara horizontal di container */
            width: 100%; /* Gunakan lebar penuh dari container */
            margin: 20px 0; /* Berikan jarak atas dan bawah */
        }

        .user-btn {
            display: flex;
            justify-content: center; /* Centers buttons horizontally in the container */
            gap: 10px; /* Adds space between buttons */
        }
    </style>
</head>
{% endblock meta %}

{% block content %}
<body>
    <div class="container">
        <h2>Add Song To User Playlist</h2>
        <div class="song-info">
            <p><strong>Judul:</strong> {{song_title}}<br>
            <strong>Artist:</strong> {{artist_name}}</p>
        </div>
        <form method="POST">
            {% csrf_token %}
            <select name="other_playlist_id" id="playlist">
                <option value="">Pilih Playlist</option>
                {% for playlist in playlists %}
                    <option value="{{ playlist.0 }}">{{ playlist.1 }}</option>
                {% endfor %}
            </select>
            <div class="actions">
                <button type="submit" class="btn btn-primary">Tambah</button>
                
            </div>
        </form>
        {% if success_message %}
            <div class="popup" id="popup">
                <p>{{ success_message }}</p>
                <form method="get" action="{% url 'playlist:playlist_detail' other_playlist %}">
                    <button type="submit" class="btn btn-primary">Ke Playlist</button>
                </form>
            </div>
            {% endif %}
            <div class="user-btn">
                <button type="button" onclick="window.history.back();">Kembali</button>
            </div>
    </div>
    <script type="text/javascript">
        function handleSubmit(event) {
            event.preventDefault(); // Prevent the default form submission
            var select = document.getElementById('playlist');
            if (select.value !== "") {
                window.location.href = 'success_add.html'; // Redirect to success page if validation is passed
            } else {
                alert('Please select a playlist first.');
            }
        }
    </script>
</body>
{% endblock content %}
</html>

play_song/templates/play_song.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

{% block meta %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Song Details</title>
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <style>
        .music-progress-container {
            width: 80%;
            margin: 20px auto;
            position: relative;
        }

        input[type="range"] {
            width: 100%;
            cursor: pointer;
        }

        .song-details {
            width: 80%;
            margin: auto;
            text-align: center;
        }

        .playlist-description{
            color: white; /* Set the text color to white */
        }

        .playlist-description p {
            margin-top: 20px; /* Jarak ke elemen di atasnya */
            margin-bottom: 20px; /* Jarak ke elemen di bawahnya */
        }
        
        .playlist-description p:first-child {
            margin-top: 20px; /* Jarak lebih besar di bagian atas elemen pertama */
        }

        .playlist-description p:last-child {
            margin-bottom: 20px; /* Jarak lebih besar di bagian bawah elemen terakhir */
        }

        .user-btn button {
            margin: 10px;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            background-color: #000; /* Initial black color */
            color: white;
            font-size: 16px;
            cursor: pointer;
            transition: background-color 0.3s; /* Transition for hover effect */
        }

        .user-btn button:hover {
            background-color: #4CAF50; /* Green when hovered */
        }

        .back-btn {
            margin: 10px;
            padding: 10px;
            border: none;
            background: none;
            cursor: pointer;
            float: left;
            color: white; /* Initial white color */
        }

        .back-btn i {
            font-size: 24px;
            transition: color 0.3s;
        }

        .back-btn:hover i {
            color: black; /* Change color on hover */
        }
    </style>
</head>
{% endblock meta %}

{% block content %}
<body>
    <div id="header-playlist">
        <div class="container">
            <nav>
              <button class="back-btn" onclick="window.history.back();"><i class="fas fa-arrow-left"></i> Back</button>
            </nav>
        </div>
    </div>
    <div class="playlist-page two">
        <h2>Song Detail</h2>
        <div class="list-playlist three">
            <div class="playlist-description">
                <p><strong>Judul:</strong> {{ song_detail.judul }}<br>
                    <strong>Genre(s):</strong> {{ song_detail.genres|join:", " }}<br>
                    <strong>Artist:</strong> {{ song_detail.artist }}<br>
                    <strong>Songwriter(s):</strong> {{ song_detail.songwriters|join:", " }}<br>
                    <strong>Durasi:</strong> {{ song_detail.durasi }} menit<br>
                    <strong>Tanggal Rilis:</strong> {{ song_detail.tanggal_rilis|date:"d/m/Y" }}<br>
                    <strong>Tahun:</strong> {{ song_detail.tahun }}<br>
                    <strong>Total Play:</strong> <span id="total-play-display">{{ song_detail.total_play }}</span><br>
                    <strong>Total Downloads:</strong> {{ song_detail.total_downloads }}<br>
                    <strong>Album:</strong> {{ song_detail.album }}
                </p>
            </div>
            <div class="music-progress-container">
                <input type="range" id="song-progress" value="0" min="0" max="100">
                <span id="progress-percentage">0%</span>
            </div>
            <div class="user-btn">
                <button onclick="playSong()">Play</button>
                <a href="add-song-to-playlist">
                    <button>Add to Playlist</button>
                </a>
                {% if show_download_button %}
                    <button>Download</button>
                {% endif %}
                <button onclick="window.history.back();">Kembali</button>
            </div>
        </div>
    </div>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
            document.getElementById('song-progress').addEventListener('input', function() {
                document.getElementById('progress-percentage').innerText = this.value + '%';
            });

            function playSong() {
                var progress = document.getElementById('song-progress').value;
                if (progress > 70) {
                    updateTotalPlays(); // Call function to update total plays
                } else {
                    alert("No action taken because progress is not greater than 70%.");
                }
            }

            function updateTotalPlay() {
                var totalPlayElement = document.querySelector('.total-play');
                var totalPlay = parseInt(totalPlayElement.innerText) + 1;
                totalPlayElement.innerText = totalPlay;
            }

            function saveTotalPlayToServer() {
                fetch(`/update-play-count/{{ song_id }}`, { method: 'POST' })
                .then(response => response.json())
                .then(data => {
                    if(!data.success) {
                        alert("Failed to permanently update play count on the server.");
                    }
                })
                .catch(error => console.error('Error updating play count on server:', error));
            }
    </script>
</body>
{% endblock content %}
</html>