2206082404-SuryaRaaviAdiputra/playlist/urls.py
from django.urls import path
from playlist.views import *

app_name = 'playlist'

urlpatterns = [
  path('', show_playlist, name='show_playlist'),
  path('playlist_detail/<str:id_playlist>', playlist_detail, name='playlist_detail'),
  path('add_playlist/', add_playlist, name='add_playlist'),
  path('delete_playlist/<str:id_playlist>', delete_playlist, name="delete_playlist"),
  path('add_song/<str:id_playlist>', add_song, name="add_song")
]

main/urls.py
from django.urls import path
from main.views import *
from melihat_chart.views import melihat_chart, daily_top,weekly_top, monthly_top, yearly_top
from play_podcast.views import play_podcast
from play_song.views import add_song_to_playlist, play_song
from play_user_playlist.views import play_user_playlist

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('user_login/', user_login, name='user_login'),
    path('register-option/', register_option, name='register_option'),
    path('register-option/register-user/', register_user, name='register_user'),
    path('register-option/register-label/', register_label, name='register_label'),
    path('homepage/', homepage, name="homepage"),
    path('logout/', logout, name="logout"),
    path('play-podcast/<uuid:podcast_id>/', play_podcast, name='play_podcast'),
    path('play-song/<uuid:song_id>/', play_song, name='play_song'),
    path('melihat-chart/', melihat_chart, name='melihat_chart'),
    path('melihat-chart/daily-top/', daily_top, name='daily_top'),
    path('melihat-chart/weekly-top/', weekly_top, name='weekly_top'),
    path('melihat-chart/monthly-top/', monthly_top, name='monthly_top'),
    path('melihat-chart/yearly-top/', yearly_top, name='yearly_top'),
    path('play-user-playlist/<uuid:user_playlist_id>/', play_user_playlist, name='play_user_playlist'),
    path('index/', index, name='index'),
    path('album_list/', album_list, name='album_list'),
    path('album_detail/<str:album_id>/', album_detail, name='album_detail'),
    path('delete_album/<str:album_id>/', delete_album, name='delete_album'),
    path('song_detail/<str:song_id>/', song_detail, name='song_detail'),
    path('delete_song/<str:song_id>/', delete_song, name='delete_song'),
    path('royalty_list/', royalty_list, name='royalty_list'),  
    path('create_album/', create_album, name='create_album'),
    path('create_song_songwriter/<str:album_id>/', create_song_songwriter, name='create_song_songwriter'),
    path('create_song_artist/<str:album_id>/', create_song_artist, name='create_song_artist'),
    path('play-song/<uuid:song_id>/add-song-to-playlist/', add_song_to_playlist, name='add_song_to_playlist'),
]

marmut/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('playlist/', include('playlist.urls')),
    path('', include('play_song.urls')),
    path('', include('melihat_chart.urls')),
]

melihat_chart/urls.py
from django.urls import path
from melihat_chart.views import melihat_chart, daily_top,weekly_top, monthly_top, yearly_top

app_name = 'melihat-chart'

urlpatterns = [
    path('melihat-chart/', melihat_chart, name='melihat_chart'),
    path('melihat-chart/daily-top/', daily_top, name='daily_top'),
    path('melihat-chart/weekly-top/', weekly_top, name='weekly_top'),
    path('melihat-chart/monthly-top/', monthly_top, name='monthly_top'),
    path('melihat-chart/yearly-top/', yearly_top, name='yearly_top'),
]

play_song/urls.py
from django.urls import path
from play_song.views import add_song_to_playlist, play_song, update_play_count

app_name = 'play_song'

urlpatterns = [
    path('play-song/<uuid:song_id>/', play_song, name='play_song'),
    path('update-play-count/<uuid:song_id>/', update_play_count, name='update-play-count'),
    path('play-song/<uuid:song_id>/add-song-to-playlist/', add_song_to_playlist, name='add_song_to_playlist'),
]

playlist/urls.py
from django.urls import path
from playlist.views import *

app_name = 'playlist'

urlpatterns = [
  path('', show_playlist, name='show_playlist'),
  path('playlist_detail/<str:id_playlist>', playlist_detail, name='playlist_detail'),
  path('add_playlist/', add_playlist, name='add_playlist'),
  path('delete_playlist/<str:id_playlist>', delete_playlist, name="delete_playlist"),
  path('add_song/<str:id_playlist>', add_song, name="add_song"),
  path('playlist_detail/delete_song/<str:id_playlist>/<str:id_song>', delete_song, name="delete_song")
]

2206082404-SuryaRaaviAdiputra/playlist/views.py
from django.shortcuts import render, redirect
from lib_database.query import *
from lib_database.playlist import *
import datetime
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
import uuid

def show_playlist(request):
  playlist = get_playlist(request.COOKIES.get("email"))
  print(playlist)
  if (len(playlist) != 0):
    print(playlist)
    pembuat = get_pembuat(request.COOKIES.get("email"))
    print(pembuat)
    Playlist.list_playlist.clear()
    for i in range(len(playlist)):
      if playlist[i][4] == None:
        Playlist(playlist[i][0], playlist[i][1], playlist[i][2], playlist[i][3], 0, playlist[i][5])
      else:
        Playlist(playlist[i][0], playlist[i][1], playlist[i][2], playlist[i][3], playlist[i][4], playlist[i][5])
    context = {
      "has_playlist": True, 
      "list_playlist": Playlist.list_playlist
    }
    return render(request, "playlist.html", context)
  return render(request, "playlist.html", context={"has_playlist": False})

def playlist_detail(request, id_playlist):
  user_detail = get_user_detail(id_playlist)
  list_song = get_detail_playlist(id_playlist)
  print(user_detail.id_playlist)
  print(id_playlist)
  print(list_song)
  Songs.list_song.clear()
  if len(list_song) != 0:
    for song in list_song:
      Songs(song[0], song[1], song[2], song[3])
    context = {
      "songs": Songs.list_song,
      "user_detail": user_detail,
      "pembuat": get_pembuat(request.COOKIES.get("email"))[0][0]
    }
    return render(request, "user_playlist_detail.html", context)
  return render(request, "user_playlist_detail.html", context={"user_detail": user_detail, "pembuat": get_pembuat(request.COOKIES.get("email"))[0][0]})

@csrf_exempt
def add_playlist(request):
  if request.method == "POST":
      email = request.COOKIES.get("email")
      judul = request.POST.get("judul")
      deskripsi = request.POST.get('deskripsi')
      id_user_playlist = uuid.uuid1()
      id_playlist = uuid.uuid1()
      insert_playlist(id_playlist, judul, deskripsi, email, id_user_playlist)
      return HttpResponseRedirect(reverse('playlist:show_playlist'))
  return render(request, "add_playlist.html")

def delete_playlist(request, id_playlist):
  del_playlist(id_playlist)
  return HttpResponseRedirect(reverse('playlist:show_playlist'))

def add_song(request, id_playlist):
  get_song = get_list_lagu()
  Songs.list_song.clear()
  for song in get_song:
    Songs(song[1], song[2], 0, song[0])
  context = {
    "list_song": Songs.list_song
  }
  return render(request, "add_song.html", context)


   
# Create your views here.

playlist/views.py
from django.shortcuts import render, redirect
from lib_database.query import *
from lib_database.playlist import *
import datetime
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
import uuid

def show_playlist(request):
  playlist = get_playlist(request.COOKIES.get("email"))
  if (len(playlist) != 0):
    Playlist.list_playlist.clear()
    for i in range(len(playlist)):
      if playlist[i][4] == None:
        Playlist(playlist[i][0], playlist[i][1], playlist[i][2], playlist[i][3], 0, playlist[i][5])
      else:
        Playlist(playlist[i][0], playlist[i][1], playlist[i][2], playlist[i][3], playlist[i][4], playlist[i][5])
    context = {
      "has_playlist": True, 
      "list_playlist": Playlist.list_playlist
    }
    return render(request, "playlist.html", context)
  return render(request, "playlist.html", context={"has_playlist": False})

def playlist_detail(request, id_playlist):
  user_detail = get_user_detail(id_playlist)
  print(user_detail)
  print("id: " + id_playlist)
  list_song = get_detail_playlist(id_playlist)
  Songs.list_song.clear()
  if len(list_song) != 0:
    for song in list_song:
      Songs(song[0], song[1], song[2], song[3])
    context = {
      "songs": Songs.list_song,
      "user_detail": user_detail,
      "pembuat": get_pembuat(request.COOKIES.get("email"))[0][0]
    }
    return render(request, "user_playlist_detail.html", context)
  return render(request, "user_playlist_detail.html", context={"user_detail": user_detail, "pembuat": get_pembuat(request.COOKIES.get("email"))[0][0]})

@csrf_exempt
def add_playlist(request):
  if request.method == "POST":
      email = request.COOKIES.get("email")
      judul = request.POST.get("judul")
      deskripsi = request.POST.get('deskripsi')
      id_user_playlist = uuid.uuid1()
      id_playlist = uuid.uuid1()
      insert_playlist(id_playlist, judul, deskripsi, email, id_user_playlist)
      return HttpResponseRedirect(reverse('playlist:show_playlist'))
  return render(request, "add_playlist.html")

def delete_playlist(request, id_playlist):
  del_playlist(id_playlist)
  return HttpResponseRedirect(reverse('playlist:show_playlist'))

@csrf_exempt
def add_song(request, id_playlist):
  get_song = get_list_lagu()
  Songs.list_song.clear()
  for song in get_song:
    Songs(song[1], song[2], 0, song[0])
  context = {
    "list_song": Songs.list_song
  }
  if request.method == "POST":
    selected_song = request.POST.get("lagu")
    try:
      insert(f"INSERT INTO PLAYLIST_SONG VALUES ('{id_playlist}', '{selected_song}');")
      for i in range(len(Playlist.list_playlist)):
        if str(id_playlist) == str(Playlist.list_playlist[i].id_playlist):
          durasi_baru = get_data(f"SELECT durasi FROM KONTEN WHERE id = '{selected_song}'")[0][0]
          Playlist.list_playlist[i].total_durasi += durasi_baru
          Playlist.list_playlist[i].jumlah_lagu += 1
         
      return redirect("playlist:playlist_detail", str(id_playlist))
    except Exception as e:
      messages.error(request, "Duplicate, tidak bisa menambahkan lagu")
  return render(request, "add_song.html", context)

def delete_song(request, id_playlist, id_song):
  del_song(id_playlist, id_song)
  durasi_baru = get_data(f"SELECT durasi FROM KONTEN WHERE id = '{id_song}'")[0][0]
  for i in range(len(Playlist.list_playlist)):
    if str(id_playlist) == str(Playlist.list_playlist[i].id_playlist):
      Playlist.list_playlist[i].total_durasi -= durasi_baru
      Playlist.list_playlist[i].jumlah_lagu -= 1
  return redirect('playlist:playlist_detail', id_playlist)



   
# Create your views here.

playlist/templates/add_playlist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta htto-equiv="X-UA-COmpatible" content="IE=edge">
    {% block meta %}
    <title>Playlist</title>
    {% endblock meta %}
    <!-- Custom styles-path -->
    <link rel="stylesheet" href="{% static 'css/playlist.css' %}">

    <!-- Font Awesome kit script -->
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>

    <!-- Google Fonts Open Sans-->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

   
</head>

{% block content %}
<body>
    <div id="header-playlist">
      <div class="container">
        <nav>
          <h5>Mar<span>mut</span></h5>
          <ul>
            <li><a href="{% url 'main:homepage' %}">Dashboard</a></li>
            <li><a href="#">Chart</a></li>
            <li><a href="{% url 'playlist:show_playlist' %}" class="nav-playlist">Kelola playlist</a></li>
            <li><a href="#">Cari lagu</a></li>
            <li><a href="#">Langganan paket</a></li>
          </ul>
          <a href="{% url 'main:logout' %}" style="text-decoration: none; cursor: pointer;">
            <button class="logout-btn">
              Logout
            </button>
          </a>
        </nav>
      </div>
    </div>
    <div class="playlist-page">
      <h2>User Playlist</h2>
      <form method="POST" class="input-playlist">
        <div id="row-title">
          <h3>Add Playlist</h3>
        </div>
        <div class="input-row">
          <div class="input-div one">
            <div>
                <h5>Judul</h5>
                <input class="input" type="text" name="judul">
            </div>
          </div>
          <div class="input-div two">
            <div>
                <h5>Deskripsi</h5>
                <input class="input" type="text" name="deskripsi">
            </div>
          </div>
          <div class="row-btn one">
            <button class="add-btn-one" type="submit">
              Tambahkan
            </button>
          </div>
        </div>
      </form>
    </div>
  <script type="text/javascript" src="/static/js/main.js"></script>
</body>
{% endblock content %}
</html>

playlist/templates/add_song.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta htto-equiv="X-UA-COmpatible" content="IE=edge">
    {% block meta %}
    <title>Daftar Lagu</title>
    {% endblock meta %}
    <!-- Custom styles-path -->
    <link rel="stylesheet" href="{% static 'css/playlist.css' %}">

    <!-- Font Awesome kit script -->
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>

    <!-- Google Fonts Open Sans-->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

   
</head>

{% block content %}
<body>
  <div id="header-playlist">
    <div class="container">
      <nav>
        <h5>Mar<span>mut</span></h5>
        <ul>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Chart</a></li>
          <li><a href="{% url 'playlist:show_playlist' %}" class="nav-playlist">Kelola playlist</a></li>
          <li><a href="#">Cari lagu</a></li>
          <li><a href="#">Langganan paket</a></li>
        </ul>
        <a href="{% url 'main:logout' %}" style="text-decoration: none; cursor: pointer;">
          <button class="logout-btn">
            Logout
          </button>
        </a>
      </nav>
    </div>
  </div>
  <div class="add-song-container">
    <form class="input-lagu" method="POST">
      {% csrf_token %}
      <div id="row-title">
        <h3>Add Song</h3>
      </div>
      <div class="input-row song">
        <div class="add-song-content">
          <h5>
            Pilih Lagu
          </h5>
            <select id="dropdown" name="lagu">
              {% for song in list_song %}
                <option value="{{song.id_lagu}}">{{ song.judul }} - {{ song.nama }}</option>
              {% endfor %} 
            </select>
          </div>
          <div class="row-btn two">
            <button class="add-btn-two" type="submit">
              Tambahkan
            </button>
          </div>
        </div>
      </div>
    </form>
  </div>
  <div style="display: inline-block; position: relative; color: red; top: -560px; left: 459px; text-decoration: none;">
  {% if messages %}  
    <ul style="list-style-type: none;">   
      {% for message in messages %}  
        <li>{{ message }}</li>  
        {% endfor %}  
    </ul>   
  {% endif %}
</div>
  <script type="text/javascript" src="/static/js/main.js"></script>
</body>
{% endblock content %}

</html>

playlist/templates/playlist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta htto-equiv="X-UA-COmpatible" content="IE=edge">
    {% block meta %}
    <title>Playlist</title>
    {% endblock meta %}
    <!-- Custom styles-path -->
    <link rel="stylesheet" href="{% static 'css/playlist.css' %}">

    <!-- Font Awesome kit script -->
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>

    <!-- Google Fonts Open Sans-->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

   
</head>

{% block content %}
<body>
    <div id="header-playlist">
      <div class="container">
        <nav>
          <h5>Mar<span>mut</span></h5>
          <ul>
            <li><a href="{% url 'main:homepage' %}">Dashboard</a></li>
            <li><a href="{% url 'melihat-chart:melihat_chart' %}">Chart</a></li>
            <li><a href="{% url 'playlist:show_playlist' %}" class="nav-playlist">Kelola playlist</a></li>
            <li><a href="#">Cari lagu</a></li>
            <li><a href="#">Langganan paket</a></li>
          </ul>
          <a href="{% url 'main:logout' %}" style="text-decoration: none; cursor: pointer;">
            <button class="logout-btn">
              Logout
            </button>
          </a>
        </nav>
      </div>
    </div>
    <div class="playlist-page">
      <h2>User Playlist</h2>
      {% if has_playlist != True %}
        <div class="list-playlist one">
          <h5>
            Anda Belum Memiliki Playlist
          </h5>
          <div class="row-btn">
            <a href="{% url 'playlist:add_playlist' %}" style="text-decoration: none; width: 100%; height: 100%; text-align: center; margin-right: 150px;">
              <button class="add-btn">
                Tambah Playlist
              </button>
            </a>
          </div>
        </div>
      {% else %}
        <div class="list-playlist two">
          <section class="playlist-content playlist">
            <table>
              <thead>
                <tr>
                  <th>Judul</th>
                  <th>Jumlah Lagu</th>
                  <th>Total Durasi</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for playlist in list_playlist %}
                  <tr>
                    <th>{{playlist.judul}}</th>
                    <th>{{playlist.jumlah_lagu}}</th>
                    <th>{{playlist.total_durasi}}</th>
                    <th>
                      <a href="{% url 'playlist:playlist_detail' playlist.id_playlist %}" style="text-decoration: none;">
                        <button>
                          Detail
                        </button>
                      </a>
                      <button>Ubah</button>
                      <a href="{% url 'playlist:delete_playlist' playlist.id_playlist %}" style="text-decoration: none;">
                        <button class="delete"><i class="fa-solid fa-circle-minus"></i></button>
                      </a>
                    </th>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </section>
          <div class="row-btn">
            <a href="{% url 'playlist:add_playlist' %}" style="text-decoration: none; width: 100%; height: 100%; text-align: center; margin-right: 150px;">
              <button class="add-btn">
                Tambah Playlist
              </button>
            </a>
          </div>
        </div>
      {% endif %}
    </div>
  <script type="text/javascript" src="/static/js/main.js"></script>
</body>
{% endblock content %}
</html>

playlist/templates/user_playlist_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta htto-equiv="X-UA-COmpatible" content="IE=edge">
    {% block meta %}
    <title>Daftar Lagu</title>
    {% endblock meta %}
    <!-- Custom styles-path -->
    <link rel="stylesheet" href="{% static 'css/playlist.css' %}">

    <!-- Font Awesome kit script -->
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>

    <!-- Google Fonts Open Sans-->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

   
</head>

{% block content %}
<body>
    <div id="header-playlist">
      <div class="container">
        <nav>
          <h5>Mar<span>mut</span></h5>
          <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Chart</a></li>
            <li><a href="{% url 'playlist:show_playlist' %}" class="nav-playlist">Kelola playlist</a></li>
            <li><a href="#">Cari lagu</a></li>
            <li><a href="#">Langganan paket</a></li>
          </ul>
          <a href="{% url 'main:logout' %}" style="text-decoration: none; cursor: pointer;">
            <button class="logout-btn">
              Logout
            </button>
          </a>
        </nav>
      </div>
    </div>
    <div class="playlist-page two">
      <h2>User Playlist Detail</h2>
      <div class="list-playlist three">
        <div class="playlist-description">
          <h3>Judul</h3>
          <h5>{{user_detail.judul}}</h5>
          <h3>Pembuat</h3>
          <h5>{{pembuat}}</h5>
          <h3>Jumlah Lagu</h3>
          <h5>{{user_detail.jumlah_lagu}}</h5>
          <h3>Total Durasi</h3>
          <h5>{{user_detail.total_durasi}} menit</h5>
          <h3>Tanggal Dibuat</h3>
          <h5>{{user_detail.tanggal_dibuat}}</h5>
          <h3>Deskripsi</h3>
          <h5>{{user_detail.deskripsi}}</h5>
        </div>
        <div class="user-btn">
          <button>Shuffle Play <i class="fa-solid fa-shuffle"></i></button>
          <button class="back-btn">
              <a href="{% url 'playlist:show_playlist' %}" style="text-decoration: none; color: white;">
              Kembali
            </button>
          </a>
        </div>
        <div id="daftar-lagu">
          <h2>Daftar Lagu</h2>
        </div>
        <section class="playlist-content two">
          <table>
            <thead>
              <tr>
                <th>Judul Lagu</th>
                <th>Oleh</th>
                <th>Durasi</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for song in songs %}
                <tr>
                  <th>{{song.judul}}</th>
                  <th>{{song.nama}}</th>
                  <th>{{song.durasi}}</th>
                  <th class="btn-action">
                    <a href="{% url 'play_song:play_song' song.id_lagu %}" style="text-decoration: none;">
                      <button><i class="fa-solid fa-eye"></i></button>
                    </a>
                    <button><i class="fa-solid fa-play"></i></button>
                    <a href="{% url 'playlist:delete_song' user_detail.id_playlist song.id_lagu %}" style="text-decoration: none;">
                      <button class="delete"><i class="fa-solid fa-circle-minus"></i></button>
                    </a>
                  </th>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </section>
        <div class="row-btn">
          <a href="{% url 'playlist:add_song' user_detail.id_playlist %}" style="text-decoration: none; width: 100%; height: 100%; text-align: center; margin-right: 150px;">
            <button class="add-btn">
              Tambah Lagu
            </button>
          </a>
        </div>
      </div>
    </div>
  <script type="text/javascript" src="/static/js/main.js"></script>
</body>
{% endblock content %}

</html>