2206082404-SuryaRaaviAdiputra/main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('login/', login, name='login'),
    path('register-option/', register_option, name='register_option'),
    path('register-option/register-user/', register_user, name='register_user'),
    path('register-option/register-label/', register_label, name='register_label'),
    path('login/homepage/', homepage, name="homepage"),
    path('logout/', logout, name="logout")
]

main/urls.py
from django.urls import path
from main.views import *
from melihat_chart.views import melihat_chart, daily_top,weekly_top, monthly_top, yearly_top
from play_podcast.views import play_podcast
from play_song.views import add_song_to_playlist, play_song
from play_user_playlist.views import play_user_playlist

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('user_login/', user_login, name='user_login'),
    path('register-option/', register_option, name='register_option'),
    path('register-option/register-user/', register_user, name='register_user'),
    path('register-option/register-label/', register_label, name='register_label'),
    path('homepage/', homepage, name="homepage"),
    path('logout/', logout, name="logout"),
    path('play-podcast/<uuid:podcast_id>/', play_podcast, name='play_podcast'),
    path('play-song/<uuid:song_id>/', play_song, name='play_song'),
    path('melihat-chart/', melihat_chart, name='melihat_chart'),
    path('melihat-chart/daily-top/', daily_top, name='daily_top'),
    path('melihat-chart/weekly-top/', weekly_top, name='weekly_top'),
    path('melihat-chart/monthly-top/', monthly_top, name='monthly_top'),
    path('melihat-chart/yearly-top/', yearly_top, name='yearly_top'),
    path('play-user-playlist/<uuid:user_playlist_id>/', play_user_playlist, name='play_user_playlist'),
    path('index/', index, name='index'),
    path('album_list/', album_list, name='album_list'),
    path('album_detail/<str:album_id>/', album_detail, name='album_detail'),
    path('delete_album/<str:album_id>/', delete_album, name='delete_album'),
    path('song_detail/<str:song_id>/', song_detail, name='song_detail'),
    path('delete_song/<str:song_id>/', delete_song, name='delete_song'),
    path('royalty_list/', royalty_list, name='royalty_list'),  
    path('create_album/', create_album, name='create_album'),
    path('create_song_songwriter/<str:album_id>/', create_song_songwriter, name='create_song_songwriter'),
    path('create_song_artist/<str:album_id>/', create_song_artist, name='create_song_artist'),
    path('play-song/<uuid:song_id>/add-song-to-playlist/', add_song_to_playlist, name='add_song_to_playlist'),
]

marmut/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('playlist/', include('playlist.urls')),
    path('', include('play_song.urls')),
    path('', include('melihat_chart.urls')),
]

playlist/urls.py
from django.urls import path
from playlist.views import *

app_name = 'playlist'

urlpatterns = [
  path('', show_playlist, name='show_playlist'),
  path('playlist_detail/<str:id_playlist>', playlist_detail, name='playlist_detail'),
  path('add_playlist/', add_playlist, name='add_playlist'),
  path('delete_playlist/<str:id_playlist>', delete_playlist, name="delete_playlist"),
  path('add_song/<str:id_playlist>', add_song, name="add_song"),
  path('playlist_detail/delete_song/<str:id_playlist>/<str:id_song>', delete_song, name="delete_song")
]

2206082404-SuryaRaaviAdiputra/main/views.py
from django.shortcuts import render, redirect
from lib_database.query import *
from lib_database.user import *
from lib_database.playlist import *
import datetime
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
def show_main(request):
    return render(request, "main.html")

@csrf_exempt
def login(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        data = search_user(email, password)
        if len(data) != 0:
            val_email = data[0][0]
            response = HttpResponseRedirect(reverse("main:homepage"))
            subscription = check_subscription(val_email)
            response.set_cookie("email", val_email)
            response.set_cookie("subscription", subscription)
           
            return response
        messages.error(request, 'Sorry, incorrect username or password. Please try again.')
    return render(request, "login.html")

def register_option(request):
    return render(request, "register_base.html")

def register_user(request):
    return render(request, "register_pengguna.html")

def register_label(request):
    return render(request, "register_label.html")

@csrf_exempt
def homepage(request):
    if check_user(request.COOKIES.get("email")) == False:
        label = get_label(request.COOKIES.get("email"))
        context = {
            "nama": label[0][1],
            "email": label[0][2],
            "kontak": label[0][4],
            "is_pengguna": False
        }
    else:
        account = get_account(request.COOKIES.get("email"))
        gender = ""
        role = ""
        has_role = get_role(request.COOKIES.get("email"))
        
        if (len(has_role) != 0):
            role += has_role[0]
            for i in range(1, len(has_role)):
                role += ", " + has_role[i]
        else: role = "Tidak mempunyai role"
        print(has_role)
        if account[0][3] == 0:
            gender = "Perempuan"
        else:
            gender = "Laki-laki"

        context = {
            "email": account[0][0],
            "username": account[0][2],
            "gender": gender,
            "tempat_lahir": account[0][4],
            "tanggal_lahir": account[0][5],
            "kota_asal": account[0][7],
            "subscription": request.COOKIES.get("subscription"),
            "role": role,
            "is_pengguna": True
        }
    return render(request, "index.html", context)

def logout(request):
    response = HttpResponseRedirect(reverse('main:show_main'))
    Songs.list_song.clear()
    Playlist.list_playlist.clear()
    response.delete_cookie('email')
    response.delete_cookie('subscription')
    
    return response

main/views.py
from django.shortcuts import render, redirect
from lib_database.query import *
from lib_database.user import *
from lib_database.playlist import *
import datetime
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
import uuid

# Create your views here.
def show_main(request):
    return render(request, "main.html")

@csrf_exempt
def user_login(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        data = search_user(email, password)
        if data == "Pengguna":
            response = HttpResponseRedirect(reverse("main:homepage"))
            subscription = check_subscription(email)
            response.set_cookie("email", email)
            response.set_cookie("subscription", subscription)
            return response
        elif data == "Label":
            response = HttpResponseRedirect(reverse("main:homepage"))
            response.set_cookie("email", email)
            return response
        messages.error(request, 'Sorry, incorrect username or password. Please try again.')
    return render(request, "login.html")

def index(request):
    email = request.user.email
    role = get_user_type(email)
    if role == "Label":
        data = get_data_label(email)
        return render(request, "index_label.html", {'id': data[0][0], 'nama': data[0][1], 'email': data[0][2], 'kontak': data[0][4]})
    else:
        return redirect('main:homepage')

def register_option(request):
    return render(request, "register_base.html")

def register_user(request):
    return render(request, "register_pengguna.html")

@csrf_exempt
def register_label(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        nama = request.POST.get("nama")
        kontak = request.POST.get("kontak")
        data = search_label(email, password)
        if len(data) != 0:
            messages.info(request, 'Email already registered')
            return render(request, "register_label.html")
        else:
            uu_id = str(uuid.uuid4())
            id_pemilik_hak_cipta = str(uuid.uuid4())
            insert_label(uu_id, nama, email, password, kontak,id_pemilik_hak_cipta)
            user = User.objects.create_user(email=email, password=password, username=uu_id)
            user.save()
            login(request, user)
            return HttpResponseRedirect(reverse('main:index_label'))
    return render(request, "register_label.html")

def royalty_list(request):
    if not request.user.is_authenticated:
        messages.info(request, 'Please login first')
        return redirect('main:user_login')
    email = request.COOKIES.get("email")
    royalty_list = get_royalty_list(email)
    name = get_user_name(email)
    return render(request, "royalty_list.html", {'royalty_list': royalty_list, 'name': name})

@csrf_exempt
def homepage(request):
    if check_user(request.COOKIES.get("email")) == False:
        label = get_label(request.COOKIES.get("email"))
        context = {
            "nama": label[0][1],
            "email": label[0][2],
            "kontak": label[0][4],
            "is_pengguna": False
        }
    else:
        account = get_account(request.COOKIES.get("email"))
        gender = ""
        role = ""
        has_role = get_role(request.COOKIES.get("email"))
        
        if (len(has_role) != 0):
            role += has_role[0]
            for i in range(1, len(has_role)):
                role += ", " + has_role[i]
        else: role = "Tidak mempunyai role"
        print(has_role)
        if account[0][3] == 0:
            gender = "Perempuan"
        else:
            gender = "Laki-laki"

        context = {
            "email": account[0][0],
            "username": account[0][2],
            "gender": gender,
            "tempat_lahir": account[0][4],
            "tanggal_lahir": account[0][5],
            "kota_asal": account[0][7],
            "subscription": request.COOKIES.get("subscription"),
            "role": role,
            "is_pengguna": True
        }
    return render(request, "index.html", context)

def logout(request):
    response = HttpResponseRedirect(reverse('main:show_main'))
    Songs.list_song.clear()
    Playlist.list_playlist.clear()
    response.delete_cookie('email')
    response.delete_cookie('subscription')
    return response

def album_list(request):
    email = request.COOKIES.get("email")
    role = get_user_type(email)
    if role == "Label":
        name = get_label_name(email)
    else :  
        name = get_user_name(email)
        
    if role == "Label":
        album_list = get_album_list_label(email)
        return render(request, "album_list_label.html", {'album_list': album_list, 'name': name})
    
    if role == "Artist" or role == "Songwriter":
        album_list = get_album_list_non_label(email)
        if role == "Artist":
            return render(request, "album_list_artist.html", {'album_list': album_list, 'name': name})
        else:
            return render(request, "album_list_songwriter.html", {'album_list': album_list, 'name': name})
    
def album_detail(request, album_id):
    song_list = get_song_list(album_id)
    album_name = get_album_name(album_id)
    return render(request, "album_list_song.html", {'song_list': song_list, 'album_name': album_name})

def delete_album(request, album_id):
    delete_album_by_id(album_id)
    return redirect('main:album_list')

def delete_song(request, song_id):
    album_id = get_album_id_by_song_id(song_id)
    delete_song_by_id(song_id)
    return redirect('main:album_detail', album_id=album_id)

def song_detail(request, song_id):
    song_detail = get_song_detail(song_id)
    album_id = get_album_id_by_song_id(song_id)
    return render(request, "song_detail.html", {'song_detail': song_detail, 'album_id': album_id})
   
def create_album(request):
    if request.method == "POST":
        album_id = str(uuid.uuid4())
        album_name = request.POST.get("album-name")
        album_label = request.POST.get("album-label")
        album_label_id = get_label_uuid_by_name(album_label)
        jumlah_lagu = 0
        total_durasi = 0
        insert_album(album_id, album_name, jumlah_lagu, album_label_id, total_durasi)
        return redirect('main:album_list')
    label_list = get_label_list()
    return render(request, "create_album.html", {'label_list': label_list})

def create_song_songwriter(request, album_id):
    songwriter_name = get_songwriter_name(request.user.username)
    artist_list = get_artist_list()
    album_name = get_album_name(album_id)
    genres = [
    "Pop",
    "Rock",
    "Hip-hop/Rap",
    "Country",
    "Jazz",
    "Blues",
    "Electronic/Dance",
    "R&B (Rhythm and Blues)",
    "Reggae",
    "Folk",
    "Indie",
    "Metal",
    "Punk",
    "Classical",
    "Latin",
    "World",
    "Funk",
    "Gospel",
    "Ambient",
    "Experimental"
]
    if request.method == "POST":
        song_id = str(uuid.uuid4())
        song_name = request.POST.get("song-name")
        song_artist_id = request.POST.get("song-artist")
        song_writer = request.POST.get("song-writer")
        song_genre = request.POST.getlist("song-genre")
        song_duration = request.POST.get("song-duration")
        add_song_songwriter(song_id, song_name, song_artist_id, song_writer, song_genre, song_duration, album_id)
        return redirect('main:album_detail', album_id=album_id)
    return render(request, "create_song_songwriter.html", {'album_name': album_name, 'songwriter_name': songwriter_name, 'artist_list': artist_list, 'genres': genres})

def create_song_artist(request, album_id):
    artist_name = get_artist_name(request.user.username)
    songwriter_list = get_songwriter_list()
    genres = [
    "Pop",
    "Rock",
    "Hip-hop/Rap",
    "Country",
    "Jazz",
    "Blues",
    "Electronic/Dance",
    "R&B (Rhythm and Blues)",
    "Reggae",
    "Folk",
    "Indie",
    "Metal",
    "Punk",
    "Classical",
    "Latin",
    "World",
    "Funk",
    "Gospel",
    "Ambient",
    "Experimental"
]
    if request.method == "POST":
        song_id = str(uuid.uuid4())
        song_name = request.POST.get("song-name")
        song_artist_name = request.POST.get("song-artist")
        song_artist_id = get_artist_id_by_name(song_artist_name)
        song_writers = request.POST.getlist("song-writer")
        song_genres = request.POST.getlist("song-genre")
        song_duration = request.POST.get("song-duration")
        add_song_artist(song_id, song_name, song_artist_id, song_writers, song_genres, song_duration, album_id)
        return redirect('main:album_detail', album_id=album_id)
    return render(request, "create_song_artist.html", {'album_name': album_id, 'artist_name': artist_name, 'genres': genres, 'songwriter_list': songwriter_list})

2206082404-SuryaRaaviAdiputra/main/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta htto-equiv="X-UA-COmpatible" content="IE=edge">
    {% block meta %}
    <title>Home</title>
    {% endblock meta %}
    <!-- Custom styles-path -->
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">

    <!-- Font Awesome kit script -->
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>

    <!-- Google Fonts Open Sans-->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

   
</head>

{% block content %}
<body>
    <div id="header">
      <div class="container">
        <nav>
          <h5>Mar<span>mut</span></h5>
          <ul>
            <li><a href="#" class="nav-dashboard">Dashboard</a></li>
            <li><a href="#">Chart</a></li>
            <li><a href="{% url 'playlist:show_playlist' %}">Kelola playlist</a></li>
            <li><a href="#">Cari lagu</a></li>
            <li><a href="#">Langganan paket</a></li>
          </ul>
          <a href="{% url 'main:logout' %}" style="text-decoration: none;">
            <button class="logout-btn">
              Logout
            </button>
          </a>
        </nav>
        <div class="dashboard-container">
          <h2>Dashboard</h2>
          <div class="user-information">
            {% if is_pengguna %}
              <div class="row row-name">
                <h5>Nama</h5>
                <div class="textfield">
                  <p>{{username}}</p>
                </div>
              </div>
              <div class="row row-email">
                <h5>Email</h5>
                <div class="textfield">
                  <p>{{email}}</p>
                </div>
              </div>
              <div class="row row-hometown">
                <h5>Kota asal</h5>
                <div class="textfield">
                  <p>{{kota_asal}}</p>
                </div>
              </div>
              <div class="row row-gender">
                <h5>Gender</h5>
                <div class="textfield">
                  <p>{{gender}}</p>
                </div>
              </div>
              <div class="row row-birthplace">
                <h5>Tempat lahir</h5>
                <div class="textfield">
                  <p>{{tempat_lahir}}</p>
                </div>
              </div>
              <div class="row row-birthdate">
                <h5>Tanggal lahir</h5>
                <div class="textfield">
                  <p>{{tanggal_lahir}}</p>
                </div>
              </div>
              <div class="row row-role">
                <h5>Role</h5>
                <div class="textfield">
                  <p>{{role}}</p>
                </div>
              </div>
            {% else %}
              <div class="row row-nama">
                <h5>Nama</h5>
                <div class="textfield">
                  <p>{{nama}}</p>
                </div>
              </div>
              <div class="row row-email">
                <h5>Email</h5>
                <div class="textfield">
                  <p>{{email}}</p>
                </div>
              </div>
              <div class="row row-kontak">
                <h5>Kontak</h5>
                <div class="textfield">
                  <p>{{kontak}}</p>
                </div>
              </div>
            {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  <div class="chart-container">
    <div class="chart-title">
      <h2>Chart</h2>
    </div>
    <div class="chart-row">
      <img src="{% static 'img/chart.png' %}">
      <h5>Nikmati pilihan lagu <br>terpopuler!</h5>
      <button class="btn-chart">
        Lihat Chart
        <i class="fa-solid fa-eye"></i>
      </button>
    </div>
  </div>
  <div class="playlist-container">
    <h2>Playlist</h2>
    <div class="playlist-row">
      <img src="{% static 'img/playlist_bg.png' %}">
      <a href="{% url 'playlist:show_playlist' %}" style="text-decoration: none;">
        <button class="btn-playlist">Tampilkan Playlist
          <a href="{% url 'playlist:show_playlist' %}" style="text-decoration: none;"></a>
        </button>
    </div>
  </div>
  <div class="paket-container">
    <h2>Langganan Paket</h2>
    <div class="btn-riwayat">
      <button>Riwayat Transaksi</button>
    </div>
    <div class="paket-row">
      <div class="paket-card">
        <div class="1-bulan">
          <h3>Premium</h3>
          <h5>1 Bulan</h5>
          <h5 class="harga">Rp54.900</h5>
          <button>Pilih Paket</button>
        </div>
        <div class="3-bulan">
          <h3>Premium</h3>
          <h5>3 Bulan</h5>
          <h5 class="harga">Rp159.000</h5>
          <button>Pilih Paket</button>
        </div>
        <div class="6-bulan">
          <h3>Premium</h3>
          <h5>6 Bulan</h5>
          <h5 class="harga">Rp499.000</h5>
          <button>Pilih Paket</button>
        </div>
        <div class="1-tahun">
          <h3>Premium</h3>
          <h5>1 Tahun</h5>
          <h5 class="harga">Rp759.000</h5>
          <button>Pilih Paket</button>
        </div>
      </div>
    </div>
  </div>
  <div class="other-container">
    <h2>Menu Lainnya</h2>
    <div class="other-row">
      <div class="download-song">
        <h3>Downloaded Songs</h3>
        <button>Kelola Downloaded Songs</button>
      </div>
      <div class="podcast">
        <h3>Podcast</h3>
        <button>Kelola Podcast</button>
      </div>
      <div class="album-songs">
        <h3>Album & Songs</h3>
        <button>Kelola Album & Songs</button>
      </div>
      <div class="album">
        <h3>Album</h3>
        <button>Kelola Album</button>
      </div>
      <div class="royalti">
        <h3>Royalti</h3>
        <button>Cek Royalti</button>
      </div>
    </div>
  </div>
  <script type="text/javascript" src="js/main.js"></script>
</body>

{% endblock content %}
</html>

2206082404-SuryaRaaviAdiputra/main/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block meta %}
    <title>Login</title>
    {% endblock meta %}
    <!-- Custom styles-path -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Font Awesome kit script -->
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>

    <!-- Google Fonts Open Sans-->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
   
</head>

{% block content %}

<body>
    <div class="container">
        <div class="back-login">
            <a href="{% url 'main:show_main' %}">
                <i class="fa-solid fa-arrow-left"></i>
            </a>
        </div>
        <div class="login-container">
            <form method="POST">
                <h2>Login</h2>
                <p>Selamat Datang di Marmut !</p>
                <div class="input-div one">
                    <div class="i">
                        <i class="fas fa-user"></i>
                    </div>
                    <div>
                        <h5>Email</h5>
                        <input class="input" type="text" name="email">
                    </div>
                </div>
                <div class="input-div two">
                    <div class="i">
                        <i class="fas fa-key"></i>
                    </div>
                    <div>
                        <h5>Password</h5>
                        <input class="input" type="password" name="password" required="">
                    </div>
                </div>
                <input type="submit" class="btn" value="Login">
                <a class="forgot" href="forgotPassword.html">Lupa kata sandi?</a>
                <div class="account">
                    <p>Belum mempunyai akun?</p>
                    <a href="{% url 'main:register_option' %}">Register</a>
                </div>
            </form>
        </div>
    </div>
    <div style="display: inline-block; position: relative; color: red; top: -386px; left: 459px">
        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}
    </div>

    <script type="text/javascript" src="/static/js/main.js"></script>
</body>

{% endblock content %}
</html>

2206082404-SuryaRaaviAdiputra/main/templates/register_label.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register Label</title>
    <!-- Custom styles-path -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Font Awesome kit script -->
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>

    <!-- Google Fonts Open Sans-->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

{% block content %}
<body>
    <div class="container"> 
      <div class="back-register-label">
        <a href="{% url 'main:register_option' %}">
            <i class="fa-solid fa-arrow-left"></i>
        </a>
      </div>
      <div class="login-container">
          <form class="register-form" action="index.html">
              <h2>Registrasi Label Marmut</h2>
          
              <div class="input-div three">
                  <div>
                      <h5>Email</h5>
                      <input class="input" type="email">
                  </div>
              </div>
              <div class="input-div three">
                  <div>
                      <h5>Password</h5>
                      <input class="input" type="password">
                  </div>
              </div>
              <div class="input-div three">
                  <div>
                      <h5>Nama</h5>
                      <input class="input" type="nama">
                  </div>
              </div>
              <div class="input-div three">
                <div>
                    <h5>Kontak</h5>
                    <input class="input" type="kontak">
                </div>
            </div>
            <div class="btn-container">
              <button
              class="btn-action">Registrasi</button>
          </div>
          </form>
      </div>
    </div>

    <script type="text/javascript" src="/static/js/main.js"></script>
</body>
{% endblock content %}
</html>
 

2206082404-SuryaRaaviAdiputra/main/templates/register_pengguna.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register Pengguna</title>
    <!-- Custom styles-path -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Font Awesome kit script -->
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>

    <!-- Google Fonts Open Sans-->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

{% block content %}
<body>
    <div class="container"> 
        <div class="back-login">
            <a href="{% url 'main:register_option' %}">
                <i class="fa-solid fa-arrow-left"></i>
            </a>
        </div>
        <div class="back-register-container">
            <form class="register-form" action="index.html">
                <div>
                    <h2>Registrasi Pengguna Marmut</h2>
                </div>
                <div class="input-div three">
                    <div>
                        <h5>Email</h5>
                        <input class="input" type="email">
                    </div>
                </div>
                <div class="input-div three">
                    <div>
                        <h5>Password</h5>
                        <input class="input" type="password">
                    </div>
                </div>
                <div class="input-div three">
                    <div>
                        <h5>Nama</h5>
                        <input class="input" type="nama">
                    </div>
                </div>
                <div class="gender-row">
                   <div>
                    <h5>Gender</h5>
                    <select id="dropdown">
                        <option value="laki-laki">Laki-laki</option>
                        <option value="perempuan">Perempuan</option>
                      </select>
                   </div>
                </div>
                <div class="input-div three">
                    <div>
                        <h5>Tempat lahir</h5>
                        <input class="input" type="tempat-lahir">
                    </div>
                </div>
                <div class="date-row">
                    <div>
                        <h5>Tanggal lahir</h5>
                        <input class="input-tanggal" type="date">
                    </div>
                </div>
                <div>
                    <div class="checkbox-group">
                        <h5>
                            Role
                        </h5>
                        <label><input type="checkbox" name="role" value="podcaster"> Podcaster</label>
                        <label><input type="checkbox" name="role" value="songwriter"> Songwriter</label>
                        <label><input type="checkbox" name="role" value="artist"> Artist</label>
                      </div>
                </div>
                <div class="btn-container">
                    <button
                    class="btn-action">Registrasi</button>
                </div>
            </form>
        </div>
    </div>

    <script type="text/javascript" src="/static/js/main.js"></script>
</body>
{% endblock content %}
</html>